In [3]:
import pandas as pd
df = pd.DataFrame([['AA', 1, 'a'],['BB', 2, 'a'],['CC', 3, 'a']], columns = ['name','value','salue'])

In [4]:
df

  name  value salue
0   AA      1     a
1   BB      2     a
2   CC      3     a

In [5]:
df.columns.values[1:] = ['prefix_' + val for val in df.columns.values[1:]]

In [6]:
df.columns.values

array(['name', 'prefix_value', 'prefix_salue'], dtype=object)

In [7]:
df

  name  prefix_value prefix_salue
0   AA             1            a
1   BB             2            a
2   CC             3            a